language: node_js
node_js:
  - "8"
sudo: required

services:
  - docker

before_install:
  - docker build -t shyamkhakhar/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shyamkhakhar/multi-docker-test npm test

after_success:
  - docker build -t shyamkhakhar/multi-client ./client
  - docker build -t shyamkhakhar/multi-nginx ./nginx
  - docker build -t shyamkhakhar/multi-server ./server
  - docker build -t shyamkhakhar/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shyamkhakhar/multi-client
  - docker push shyamkhakhar/multi-server
  - docker push shyamkhakhar/multi-nginx
  - docker push shyamkhakhar/multi-worker
